NewDbCollegeProj/Controllers/LatestUpdatesController.cs
using System;
using System.Collections.Generic;
using NewDbCollegeProj.ViewModels;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NewDbCollegeProj.Models;

namespace newProjectClg.Controllers
{
    public class LatestUpdatesController : Controller
    {
        newDbClgEntities db = new newDbClgEntities();

        public DateTime? CreatedDate { get; set; }
        
        public ActionResult Update()
        {

            /*List<Student> student = new List<Student>();
            List<Teacher> teacher = new List<Teacher>();
            List<LatestUpdate> latestUpdate = new List<LatestUpdate>();*/

            var query = (from u in db.LatestUpdates
                         where u.Createdby== 10

                         select new
                         LatestUpdateVM

                         {
                             Created_Date = u.Created_Date,
                             Information = u.Information,
                             Name = "Admin"

                         }).ToList()

            .Union

            (from u in db.LatestUpdates

             join t in db.Teachers on u.Createdby equals t.User_Id into teacherGroup

             from t in teacherGroup.DefaultIfEmpty().ToList()

             join s in db.Students on u.Createdby equals s.User_Id into studentGroup

             from s in studentGroup.DefaultIfEmpty().ToList()
             

             where u.Createdby != 10 

             select new
             LatestUpdateVM
             {
                    Created_Date=u.Created_Date,

                 Information = u.Information,
                 Name = t.Name ?? s.Name

             });
            return View(query.ToList());

            /*return View(db.LatestUpdates.ToList());*/

        }


        [HttpPost]
        public ActionResult Update(LatestUpdate l)
        {

            if (string.IsNullOrEmpty(l.Information))
            {
                // Both username and password are empty
                ModelState.AddModelError("", "please enter text first");
                return RedirectToAction("Update"); // Return the login view with the error message
            }
            if (ModelState.IsValid)
            {
                
                LatestUpdate lu = new LatestUpdate();
                lu.Created_Date = DateTime.Now;
                lu.Information = l.Information;
                lu.Createdby = l.Createdby;
                db.LatestUpdates.Add(lu);
                db.SaveChanges();
                return RedirectToAction("Update");


                
            }
            return View(l);
        }
    }
}

NewDbCollegeProj/Controllers/TeachersDetailsController.cs
using NewDbCollegeProj.Models;
using NewDbCollegeProj.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewDbCollegeProj.Controllers;

namespace NewDbCollegeProj.Controllers
{
    public class TeachersDetailsController : Controller
    {

        
       

        newDbClgEntities db = new newDbClgEntities();
        // GET: TeachersDetails
        public ActionResult Index()
        {
            List<User> students = db.Users.ToList();
            return View(students);
        }

        [HttpGet]
        public ActionResult RegisterTeacher()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegisterTeacher(TeacherRegVM obj)
        {
            string Department = obj.Department;
            if (string.IsNullOrEmpty(obj.Username) || string.IsNullOrEmpty(obj.Password))
            {

                ModelState.AddModelError("", "Please enter all details");
                return View(obj); // Return the login view with the error message
            }
            string hashedPassword = HashingHelper.HashPassword(obj.Password);// why hashedPassword storing here(since no column in table)
            //Veryfying whether the email already exists
            var isEmailAlreadyExists = db.Teachers.Any(x => x.Email == obj.Email);
            if (isEmailAlreadyExists)
            {
                ModelState.AddModelError("Email", "User with this email already exists");
                return View(obj);
            }
            //Veryfying whether the username already exists
            var isUserNameAlreadyExists = db.Users.Any(x => x.Username == obj.Username);
            if (isUserNameAlreadyExists)
            {
                ModelState.AddModelError("UserName", "User with this username already exists");
                return View(obj);
            }

            //Employee_id generation
            var results = (from tt in db.Teachers



                           orderby tt.Employee_Id descending
                           let EmployeeId = tt.Employee_Id.Substring(3, 6)
                           select new
                           {
                               EmployeeId
                           }
                       ).FirstOrDefault();




            int count;



            if (results == null)
            {
                count = 1;
            }
            else
            {
                count = Int32.Parse(results.EmployeeId) + 1;
            }
            String Employ = "VNR" + Convert.ToString(count).PadLeft(3, '0');

            User u = new User();
            u.Username = obj.Username;
            u.Password = hashedPassword;
            u.Status = true;
            u.User_Type = 2;
            db.Users.Add(u);
            db.SaveChanges();

            Teacher t=new Teacher();
            t.Name = obj.Name;
            t.Gender = obj.Gender;
            t.Department = obj.Department;
            t.Employee_Id = Employ;
            t.Phone_Number = obj.Phone_Number;
            t.Email = obj.Email;    
            t.User_Id=u.Id;
            db.Teachers.Add(t);
            db.SaveChanges();

            Address a = new Address();
            a.Door_Number = obj.Door_Number;
            a.Street = obj.Street;
            a.Area = obj.Area;
            a.City = obj.City;
            a.Pincode = obj.Pincode;
            a.Teacher_Id  = t.Id;
            db.Addresses.Add(a);
            db.SaveChanges();



            return RedirectToAction("home", "Home");
        }
    }
}

NewDbCollegeProj/Views/Shared/_Create.cshtml
@model NewDbCollegeProj.Models.LatestUpdate
@using (Html.BeginForm("Update", "LatestUpdates", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{ 
        <div class="form-horizontal">
            <br />
            <h4 style="color: #28104E;">Enter Your Updates</h4>
            <div>@Html.ValidationSummary(true, "", new { @class = "text-danger" })</div>


            <div class="container">
                <div class="form-group">
                    <div class="flex-container">
                        <div class="textarea-container">

                            @Html.TextAreaFor(model => model.Information, new { style = "width:800px; height:100px", @class = "form-control", placeholder = "Enter your information here..." })
                            @Html.ValidationMessageFor(model => model.Information, "", new { @class = "text-danger" })
                        </div>
                        <div class="button-container" style="margin-top:10px;">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
            @if (User.IsInRole("Teacher"))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Createdby, htmlAttributes: new { style = "display: none;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Createdby, new { htmlAttributes = new { style = "display: none;", Value = @Session["TeacherId"] } })
                    </div>
                </div>
            }
            else if (User.IsInRole("Student"))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Createdby, htmlAttributes: new { style = "display: none;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Createdby, new { htmlAttributes = new { style = "display: none;", Value = @Session["StudentId"] } })
                    </div>
                </div>
            }
            else if (User.IsInRole("Admin"))
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Createdby, htmlAttributes: new { style = "display: none;" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Createdby, new { htmlAttributes = new { style = "display: none;", Value = 10 } })
                    </div>
                </div>
            }
        </div>
}

NewDbCollegeProj/Views/Shared/_Layout.cshtml
@using NewDbCollegeProj.Models
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>
    <style>
        /*.horizontal-list {
            display: flex;
            list-style: none;
        }

            .horizontal-list li {
                margin-right: 10px;
            }*/
        /*body {
            overflow-y: hidden;
        }*/
        .graduation-icon {
            color: navajowhite; /* Set the color of the icon */
            font-size: 24px; /* Set the size of the icon */
        }

        ​
        .navbar {
            min-height: 32px !important;
        }

            .navbar .navbar-nav {
                list-style-type: none;
                float: none;
               
            }

        .navbar .navbar-nav li a {
            color: white;
        }
        .navbar {
            background-color: #03a9f4;
            text-align: center;
            padding-top: 5px;
            box-shadow: 20px 20px 20px #cbced1, -13px -13px 20px #fff;
        }

        .navbar {
            font-family: "Times New Roman", Times, serif;
            font-size: 20px;
            border:0;
        }

        li.right {
            float: right;
        }
        li.left {
            display: inline-block;
        }
        
        </style>
    <body>

       @* <nav class="navbar navbar-default" style="background-color:darkblue">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a style="font-size:30px;margin-top:18px;" class="navbar-brand" href="#">VNR </a>
                    </div>
                    <ul class="nav navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            string TeacherName1 = "";
                            string StudentName1 = "";
                            if (User.IsInRole("Admin"))
                            {
                                <li style="margin-left:50px;color:whitesmoke">@Html.ActionLink("Teacher", "RegisterTeacher", "TeachersDetails")</li>
                                <li style="margin-left: 50px"><a href="/Students/RegisterStudent">Student</a></li>
                                <li style="margin-left: 50px"><a href="#">Time-Table</a>
                                 </li><li style="margin-left: 50px;margin-right:100px;"><a href="/LatestUpdates/Update">Latest Update</a></li>
                                <li style="margin-left: 200px;margin-top:40px"> <b>Admin</b></li>
                                Session["Admin"] = "Admin";
                            }
                            else if (User.IsInRole("Teacher"))
                            {
                                using (var context = new newDbClgEntities())
                                {
                                    var id = (from usertable in context.Users
                                              where usertable.Username == @User.Identity.Name
                                              select usertable.Id);
                                    int id2 = id.FirstOrDefault();
                                    Session["TeacherId"] = id2;
                                    //Teacher welcome name
                                    var TeacherName = (from usertable in context.Teachers
                                                       where usertable.User_Id == id2
                                                       select usertable.Name);
                                    TeacherName1 = TeacherName.FirstOrDefault();
                                    Session["Teacher"] = "Teacher";





                                    <li style="margin-left: 50px"><a href="/Students/RegisterStudent">Student</a></li>
                                    <li style="margin-left: 50px"><a href="#">Time-Table</a></li>
                                    <li style="margin-left: 50px"><a href="/LatestUpdates/Update">Latest Update</a></li>
                                    <li style="margin-left: 200px;margin-top:40px">  @TeacherName1 </li>
                                }

                            }
                            else if (User.IsInRole("Student"))
                            {

                                using (var context = new newDbClgEntities())
                                {
                                    var id = (from usertable in context.Users
                                              where usertable.Username == @User.Identity.Name
                                              select usertable.Id);
                                    int id2 = id.FirstOrDefault();
                                    Session["StudentId"] = id2;
                                    var StudentName = (from usertable in context.Students
                                                       where usertable.User_Id == id2
                                                       select usertable.Name);
                                    StudentName1 = StudentName.FirstOrDefault();
                                    Session["Student"] = "Student";

                                    <li style="margin-left: 50px"><a href="#">Time-Table</a></li>
                                    <li style="margin-left: 50px"><a href="/LatestUpdates/Update">Latest Update</a></li>
                                    <li style="margin-left: 200px;margin-top:40px">  @StudentName1</li>
                                }
                            }

                            <li style="padding-left: 30px; margin-top: 35px; color: #777779">
                                <button class="btn"><a href="/Home/Logout"><b>Logout</b></a></button>
                            </li>

                        }
                        else
                        {
                            <li style="padding-left: 1030px; margin-top: 25px; color: #777779">
                                <button class="btn"><a href="/Home/Login"><b>Login</b></a></button>
                            </li>
                        }
                    </ul>
                </div>
                <br />
            </nav>*@



        @*new navbar*@
        <nav class="navbar navbar-inverse">
            <div class="container">

                <ul class="nav navbar-nav">

                    @if (User.Identity.IsAuthenticated)
                    {<li><a href="/Home/home"><span style="color:navajowhite;" class="fa fa-graduation-cap"></span>VNR</a></li>
                        if (User.IsInRole("Admin"))
                        {
                            <li><a href="/TeachersDetails/RegisterTeacher">Teacher</a></li>
                            <li><a href="/Students/RegisterStudent">Student</a></li>
                            <li><a href="/LatestUpdates/Update">Latest Update</a></li>
                            <li><a href="/TimeTable/Index">Time Table</a></li>
                            <li class="dropdown right">
                                <a style="background-color: #03a9f4" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa-solid fa-user"></i><span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a style="color:black;font-weight:bolder;font-size:18px;" href="#">Admin</a></li>
                                    <li><a style="color:black" href="/Home/Logout">Logout</a></li>
                                </ul>
                            </li>
                        }
                        else if (User.IsInRole("Teacher"))
                        {
                            using (var context = new newDbClgEntities())
                            {

                                var id = (from usertable in context.Users
                                          where usertable.Username == @User.Identity.Name
                                          select usertable.Id);
                                int id2 = id.FirstOrDefault();
                                Session["TeacherId"] = id2;
                                //Teacher welcome name
                                var TeacherName = (from usertable in context.Teachers
                                                   where usertable.User_Id == id2
                                                   select usertable.Name);
                                string TeacherName1 = TeacherName.FirstOrDefault();
                                Session["Teacher"] = "Teacher";
                                <li><a href="/Students/RegisterStudent">Student</a></li>
                                <li><a href="/LatestUpdates/Update">Latest Update</a></li>
                                <li><a href="/TimeTable/Index">Time Table</a></li>
                                <li class="dropdown right">
                                    <a style="background-color: #03a9f4" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa-solid fa-user"></i><span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a style="color:black;font-weight:bolder;font-size:18px;" href="#">@TeacherName1</a></li>
                                        <li><a style="color:black" href="/Home/Logout">Logout</a></li>
                                    </ul>
                                </li>
                            }
                        }
                        else if (User.IsInRole("Student"))
                        {
                            using (var context = new newDbClgEntities())
                            {
                                var id = (from usertable in context.Users
                                          where usertable.Username == @User.Identity.Name
                                          select usertable.Id);
                                int id2 = id.FirstOrDefault();
                                Session["StudentId"] = id2;
                                var StudentName = (from usertable in context.Students
                                                   where usertable.User_Id == id2
                                                   select usertable.Name);
                                string StudentName1 = StudentName.FirstOrDefault();
                                Session["Student"] = "Student";
                                <li><a href="/LatestUpdates/Update">Latest Update</a></li>
                                <li><a href="/TimeTable/Index">Time Table</a></li>
                                <li class="dropdown right">
                                    <a style="background-color: #03a9f4" class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa-solid fa-user"></i><span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a style="color:black;font-weight:bolder;font-size:18px;" href="#">@StudentName1</a></li>
                                        <li><a style="color:black" href="/Home/Logout">Logout</a></li>
                                    </ul>
                                </li>
                            }
                        }
                    }
                    else
                    {
                        <li class="left" style="font-size: 28px; font-family: 'Times New Roman', Times, serif;"><a href="#" style="color:white;">VNR Institute Of Management</a></li>
                        <!--<li>
        <ul class="horizontal-list">
            <li class="left" style="font-size:35px; color:whitesmoke;"><a href="#">VNR Institute Of Management</a></li>-->
                        @*                                    <li><a href="/Home/Login">Login</a></li>
                        *@
                        <!--</ul>
        </li>-->
                    }


                </ul>
            </div>

        </nav>




        <div class="container">

            @RenderBody()

        </div>
        


        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>